version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend:latest
    working_dir: /app
    # volumes:
    #   - ./frontend:/app
    ports:
      - "8000:8000"
    environment:
      - BACKEND_API_URL=https://api.subedimukti.com.np
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: backend:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      MYSQL_HOST: db  # This should be the name of the db service
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: userpasswordc
      MYSQL_DATABASE: myapp
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpasswordc
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge