apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: prod
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
  namespace: prod
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: prod
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: prod
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
