#BACKEND Secret
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
data:
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: dXNlcnBhc3N3b3Jk
  MYSQL_DATABASE: bXlhcHA=

---
#MYSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prod
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: bXlhcHA=
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: dXNlcnBhc3N3b3Jk

---
#BACKEND CONFIG MAP (LIKE ENV VARIABLE)
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: prod
data:
  FLASK_APP: "app.py"
  FLASK_RUN_HOST: "0.0.0.0"
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"

