#FRONTEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port on which the Service is exposed within the cluster
      targetPort: 8000 # The port the request is forwarded to inside the Pod
      nodePort: 30001
---
#BACKEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prod
spec:
  type: NodePort # Actually This is very bad practice. 
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000 # The port on which the Service is exposed within the cluster
      targetPort: 5000 # The port the request is forwarded to inside the Pod
      nodePort: 30002 # We shouldn't expose the backend publicly.
  

---
#MYSQL SERVICE
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: prod
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306 # The port on which the Service is exposed within the cluster
      targetPort: 3306 # The port the request is forwarded to inside the Pod
  clusterIP: None

